import { useEffect, useRef } from 'react'
import { MessagesSquare } from 'lucide-react'
import { Composer } from './Composer'
import { MessageRow } from './MessageRow'
import { SuggestionChips } from './SuggestionChips'
import type { Message } from '@/hooks/useChat'

export function ChatPanel({
  messages,
  isAsking,
  stageIndex,
  draft,
  onDraftChange,
  onSend,
  onStop,
  onRetry,
  repositoryName,
  repositoryId,
}: {
  messages: Message[]
  isAsking: boolean
  stageIndex: number
  draft: string
  onDraftChange: (value: string) => void
  /** Called with a suggestion, or with nothing when the user hits send. */
  onSend: (question?: string) => void
  onStop: () => void
  onRetry: () => void
  repositoryName: string
  /** Needed to resolve citation paths into real file contents. */
  repositoryId?: number
}) {
  const bottomRef = useRef<HTMLDivElement>(null)
  const isEmpty = messages.length === 0

  // Keep the newest content in view as the transcript grows.
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  }, [messages, isAsking])

  useEffect(() => {
    if (!isEmpty) return
    bottomRef.current?.scrollIntoView({ block: 'end' })
  }, [isEmpty])

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="mx-auto w-full max-w-3xl px-4 py-6 sm:px-6">
          {isEmpty ? (
            <div className="flex min-h-[52vh] flex-col justify-center">
              <div className="mb-8 text-center">
                <span className="mx-auto mb-4 inline-flex size-12 items-center justify-center rounded-2xl border border-line bg-surface text-accent">
                  <MessagesSquare className="size-5" />
                </span>
                <h2 className="text-xl font-semibold tracking-tight text-fg">
                  Ask anything about your repository
                </h2>
                <p className="mx-auto mt-1.5 max-w-md text-[13.5px] leading-relaxed text-muted">
                  {repositoryName} has been parsed, chunked and embedded. Questions are
                  answered only from code that was actually found.
                </p>
              </div>
              <SuggestionChips onSelect={(question) => onSend(question)} />
            </div>
          ) : (
            <div className="space-y-6">
              {messages.map((message) => (
                <MessageRow
                  key={message.id}
                  message={message}
                  isAsking={isAsking}
                  stageIndex={stageIndex}
                  onRetry={onRetry}
                  repositoryId={repositoryId}
                />
              ))}
            </div>
          )}
          <div ref={bottomRef} className="h-px" />
        </div>
      </div>

      <div className="border-t border-line bg-canvas-soft/80 backdrop-blur">
        <div className="mx-auto w-full max-w-3xl px-4 py-3 sm:px-6">
          <Composer
            value={draft}
            onChange={onDraftChange}
            onSend={onSend}
            onStop={onStop}
            isAsking={isAsking}
          />
          <p className="mt-2 text-center text-[11px] text-faint">
            Answers are generated by retrieval-augmented generation and may be incomplete.
            Always verify against the cited source.
          </p>
        </div>
      </div>
    </div>
  )
}
